version: 2
updates:
    - package-ecosystem: "npm" # See documentation for possible values
      directories:
          - "**/*"
      schedule:
          interval: "daily"
      commit-message:
          prefix: "deps"
          prefix-development: "deps(dev)"
